# Generated by Django 5.0.4 on 2024-05-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('brought_by', models.CharField(max_length=100)),
                ('time_of_arrival', models.DateTimeField(auto_now_add=True)),
                ('parent_names', models.CharField(max_length=200)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_of_stay', models.CharField(max_length=100)),
                ('baby_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProcuredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('NIN', models.CharField(max_length=20)),
                ('recommender_name', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(max_length=100)),
                ('sitter_number', models.CharField(max_length=20)),
                ('contacts', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabyDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departed_by', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
            ],
        ),
        migrations.CreateModel(
            name='ResoldDoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resold_dolls', to='core.procureditem')),
            ],
        ),
    ]
